server:
  port: 8091
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
productqueue:
  rabbitmq:
    exchange: produtc.exchange
    queue: product.queue
    routingkey: product.routingkey
