server:
  port: 8074
spring:
  application:
    name: productselect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

  security:
    basic:
      enable: false
    ignored: /**

 # jpa:
 #   database: H2
 #   hibernate:
 #     ddl-auto: update

  jmx:
    enabled: false

#  datasource:
#    url: jdbc:mysql://sql-product-pod:3306/productdb?createDatabaseIfNotExist=true&autoReconnect=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver


productselectionqueue:
  rabbitmq:
    exchange: productselection.exchange
    queue: productselection.queue
    routingkey: productselection.routingkey
