server:
  port: 8073
spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  security:
    basic:
      enable: false
    ignored: /**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://mysql-container:3306/orderdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: mtsds
    password: mtsds
    platform: mysql
    initialization-mode: always

orderqueue:
  rabbitmq:
    exchange: order.exchange
    queue: order.queue
    routingkey: order.routingkey
