server:
  port: 8072
spring:
  application:
    name: cart-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  security:
    basic:
      enable: false
    ignored: /**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://mysql-container:3306/cartdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql
    initialization-mode: always

cartqueue:
  rabbitmq:
    exchange: cart.exchange
    queue: cart.queue
    routingkey: cart.routingkey

productqueue:
  rabbitmq:
    exchange: product.exchange
    queue: product.queue
    routingkey: product.routingkey
