server:
  port: 8072
spring:
  application:
    name: cartloader
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  security:
    basic:
      enable: false
    ignored: /**

  jmx:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

productselectionqueue:
  rabbitmq:
    exchange: productselection.exchange
    queue: productselection.queue
    routingkey: productselection.routingkey